### ISSUE TITLE
DMP training resources and lesson plans

### ISSUE THREAD

**Issue by jennyostrop** [DHP-stottepakke/pages#27]
**What topic do you wish to add?**
Adding a page in the knowledge base with existing DMP training resources and lesson plans.

**Are there existing pages in the website related to the requested page?**
Empty page generated: https://dhp-stottepakke.github.io/pages/dmp_training

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

[EIFL Digital Research Literacy Training programme (revised 2024)](https://www.eifl.net/news/eifl-digital-research-literacy-training-programme-1)
- [Writing a DMP](https://eifl.net/programme/digital-research-literacy/writing-data-management-plan-dmp)
- [Managing and sharing research data](https://www.eifl.net/programme/digital-research-literacy/managing-and-sharing-research-data)

FAIR teaching handbook (2021, [archived on zenodo](https://zenodo.org/records/6674301))
- [Lesson plan DMP](https://fairsfair.gitbook.io/fair-teaching-handbook/0lessonplans/2lessonplan)

Data One: Data Management Planning Skillbuilding Hub (2020)
- [Data Management Planning](https://dataoneorg.github.io/Education/lessons/03_planning/)

**Comment by korbinib** [comment]
There is various sets of material collections within ELIXIR in [TeSS](https://tess.elixir-europe.org/search?q=%22data+management+plan%22#materials)  not sure if this fits 100% here:

**Comment by jennyostrop** [comment]
I believe most relevant for us are "train the trainer"-type materials?
