### ISSUE TITLE
Mapping to cycle

### ISSUE THREAD

**Issue by sveinho** [DHP-stottepakke/pages#4]
**What topic do you wish to add?**
Defining research data cycle from beginning to end, defining some stages and/ or subprocesses

**Are there existing pages in the website related to the requested page?**
Suggest this as a "hidden page" for internal use, meaning for project and support staff

**Resources**
We can choose among many existing cycle descriptions 

**Context**
The context is the project, for possible shared thoughts on the linkage between questions in dmp and part in cycle

**Comment by jennyostrop** [comment]
@sveinho Which data life cycle models do you think should be covered?

The minimalistic phases that we discussed: planning, active phase, publishing

Life cycle that is used e.g. in the RDMkit, which is close to the DMP pilot: https://rdmkit.elixir-europe.org/data_life_cycle

CESSDA has slightly other stages: https://dmeg.cessda.eu/Data-Management-Expert-Guide

ALLEA starts with "identifying data": https://repository.dri.ie/catalog/tq582c863

**Comment by LLongva** [comment]
Jeg liker nok best RDMkit-modellen. Den er velkjent, og jeg synes den har den mest logiske gangen. ALLEA-modellen introduserer  en 'identify'-fase før planlegging. Kanskje det er et poeng i humaniora, å identifisere hva som er datagrunnlaget, før man går til planlegging. Men jeg mener det er mest logisk at denne identifiseringen er en del av planleggingen. CESSDA-modellen er rar i og med at 'collecting/generating data' mangler. Men dette er inkludert i 'Organise & Document', etter det jeg kan se. Men altså: jeg holder en knapp på RDMkit-modellen.

**Comment by sveinho** [comment]
Hvis vi sammenligner RDM-kit mot DSW (i parentes), så forstår jeg det som om en mapping mellom syklus og DSW blir omtrent slik: 

Plan
Collect (includes possibly also re-using data, as well as creating and collecting data) 
Process (includes to some degree the planning of storage use)
Analyse (similarities to interpreting data in DSW)
Preserve (includes also the process of archiving in DSW) 
Share (similar to the wording publishing metadata and/or data, similar also to giving access to data)
