### ISSUE TITLE
Contribution - style guide

### ISSUE THREAD

**Issue by kjemist** [DHP-stottepakke/pages#5]
**What topic do you wish to add?**
For the «how to contribute» page, a new subpage will be created which will serve as a style guide for contributors

**Are there existing pages in the website related to the requested page?**
No

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular institution, infrastructure, project, domain, or use-case please list them below:

University library of Bergen

**Comment by kjemist** [comment]
Added first draft 23.01.24

**Comment by korbinib** [comment]
closed by #14
