### ISSUE TITLE
6a - Who (for example role, position, and institution) will be responsible for data management (i.e. the data steward)?

### ISSUE THREAD

**Issue by LLongva** [DHP-stottepakke/pages#6]
**Link to the page of interest**
http://dhp-stottepakke.github.io/pages/6_responsibilities_resources

**Describe what you would change to the page**

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name
- Link
- Description

**Comment by korbinib** [comment]
see #15

**Comment by korbinib** [comment]
closed in #21
