### ISSUE TITLE
KM editor error

### ISSUE THREAD

**Issue by sveinho** [DHP-stottepakke/pages#78]
![issue_km_editor](https://github.com/user-attachments/assets/7eefeb7f-ad53-4f3a-ae87-4253764021cb)

Problem med parsing av beskrivende tekst?

**Comment by korbinib** [comment]
Fixed. Typo in commenting delimiter `<! -- SH:` changed to `<!-- SH:`

**Comment by sveinho** [comment]
Thanks, and sorry..
